Improve sharable feature.
novius-os/noviusos_blognews pull request #17
Opened 2016-11-17 09:50 UTC by SwithFr

Simple sharing on social media needs some open graph meta.

- Add sharable properties for news CRUD (title, image and description)
- Possibility to disable properties with config.

2016-11-17 10:14 UTC, Meroje commented
You don't need new fields, use the content nugget https://github.com/novius-os/noviusos_blognews/blob/c0c29d9/classes/model/post.model.php#L159-L198

2016-11-17 11:17 UTC, SwithFr commented
Removed new fields and use content nugget instead.

2016-11-17 11:20 UTC, Meroje approved these changes

2016-11-17 16:51 UTC, jguyomard requested changes

2016-11-17 16:51 UTC, jguyomard commented on classes/controller/front.ctrl.php
> +            $img_id = isset($sharableData['image']) ? (int)$sharableData['image'] : isset($post->medias->thumbnail) ? $post->medias->thumbnail->url() : null;
camelCase?

2016-11-17 16:51 UTC, jguyomard commented on config/controller/admin/post.config.php
> +                        $category_class = $namespace . '\\Model_Category';
please use concat_without_space style

2016-11-17 16:51 UTC, jguyomard commented on config/controller/admin/post.config.php
> +                        $item->categories = $category_class::find('all', array('where' => array(array('cat_id', 'IN', (array)$data['categories']))));
keep space after (array)

2016-11-17 16:51 UTC, jguyomard commented on classes/controller/front.ctrl.php
> +            $this->main_controller->addMeta('<meta property="og:title" content="' . $title . '" />');
please use concat_without_space style

2016-11-18 07:49 UTC, jguyomard approved these changes

2016-11-21 08:46 UTC, merged